### ISSUE TITLE
Add blackbox probe to monitor zcp public add-on service and business application

### ISSUE THREAD

**Issue by zodiac12k** [cnpst/zcp-monitoring#11]
Cloud Z CP Public add-on service 들의 상태와 실제 critical business impact 가 있는 business application 을 외부 접근에 대한 상태를 모니터링하기 위해서 prometheus job 에 blackbox probe 를 추가하거나 job 설정을 변경한다.

**Comment by zodiac12k** [comment]
```
    additionalScrapeConfigs:
      ## Monitor internal Kubernetes services
      # Blackbox-exported should be installed separately via https://github.com/helm/charts/tree/master/stable/prometheus-blackbox-exporter
      - job_name: 'kubernetes-services'
         # blackbox-exporter path to scrape
        metrics_path: /probe
        params:
          module: [http_2xx]
        kubernetes_sd_configs:
        - role: service
        relabel_configs:

        # 1. Example relabel to probe only some services that have "example.io/should_be_probed = true" annotation
        - source_labels: [__meta_kubernetes_service_annotation_example_io_should_be_probed]
          action: keep
          regex: true

        # 2. Save address in a separate label
        - source_labels: [__address__]
          target_label: __param_target

        # 3. Replace address with an internal blackbox service so scraper is always pointed at blackbox-exporter
        - target_label: __address__
          replacement: blackbox-exporter-service:9115

        # 4. Save address in an instance label since __param_target is going to be dropped
        - source_labels: [__param_target]
          target_label: instance

        # 5. Save module in an module label since __param_module is going to be dropped
        - source_labels: [__param_module]
          target_label: module

        # 6. Add namespace and service name labels
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_service_name]
          target_label: kubernetes_name
```
Refers to https://github.com/coreos/prometheus-operator/issues/256
