### ISSUE TITLE
Optimize the resources such as cpu, memory requests and limits

### ISSUE THREAD

**Issue by zodiac12k** [cnpst/zcp-monitoring#16]
각 component의 deployment, daemonset 에 지정하는 다음 resource 들을 최적화한다. resource 지정이 되어 있지 않은 component 도 모두 지정한다.
* cpu requests
* cpu limits
* memory requests
* memory limits

ex)
```yaml
          resources:
            limits:
              cpu: 4000m
              memory: 4Gi
            requests:
              cpu: 3000m
              memory: 3Gi
```
