### ISSUE TITLE
Add readiness, liveness probe unspecified in several component

### ISSUE THREAD

**Issue by zodiac12k** [cnpst/zcp-monitoring#17]
일부 component 에서 readiness, liveness probe 가 지정되어 있지 않아 pod 의 상태를 확인할 수 없어 추가가 필요하다.
ex)
``` yaml
          livenessProbe:
            httpGet:
              path: /
              port: 9000
          readinessProbe:
            httpGet:
              path: /
              port: 9000
```
