### ISSUE TITLE
Improve ZCPMonitoringDown alert rule

### ISSUE THREAD

**Issue by zodiac12k** [cnpst/zcp-monitoring#26]
ZDB grafana component 의 문제로 `ZCPMonitoringDown` Alert 이 발생했을 때 ZCP grafana 의 문제인지 ZDB grafana 의 문제인지 구분하기 힘들어서 다음과 같이 Alert Rule 을 개선

> Before

```
alert: ZCPMonitoringDown
expr: up{component=~"alertmanager|blackbox-exporter|grafana|kube-state-metrics|prometheus"}
  == 0
for: 2m
labels:
  channel: default
  priority: P4
  product: zcp-public
  severity: critical
annotations:
  description: ZCP Monitoring Component Down has failed for {{ $labels.component }}
  summary: ZCP Monitoring Component Down
```

> After

```
alert: MonitoringComponentDown
expr: up{component=~"alertmanager|blackbox-exporter|grafana|kube-state-metrics|prometheus"}
  == 0
for: 2m
labels:
  channel: default
  priority: P4
  product: zcp-public
  severity: critical
annotations:
  description: Monitoring Component Down has failed for {{ $labels.namespace }}/{{ $labels.component }}
  summary: Monitoring Component Down
```
