### ISSUE TITLE
Simplify grafana global variable setting

### ISSUE THREAD

**Issue by zodiac12k** [cnpst/zcp-monitoring#36]
grafana.ini 파일에서 클러스터 별로 다르게 설정되는 부분을 단순화

아래 예제의 grafana.ini 설정을
```ini
[server]
domain = ***-monitoring.cloudzcp.io
...
[auth.generic_oauth]
auth_url = https://***-iam.cloudzcp.io/auth/realms/zcp/protocol/openid-connect/auth
```
grafana-deployment 의 env 에 GF_* 변수를 활용하여 설정하도록 변경
```yaml
...
  containers:
  - env:
    - name: GF_SERVER_DOMAIN
      value: ***-monitoring.cloudzcp.io
    - name: GF_AUTH_GENERIC_OAUTH_AUTH_URL
      value: https://***-iam.cloudzcp.io/auth/realms/zcp/protocol/openid-connect/auth
...
```
