### ISSUE TITLE
remove unused prometheus rule labels

### ISSUE THREAD

**Issue by zodiac12k** [cnpst/zcp-monitoring#66]
실제 사용이 되지 않은 prometheus rule label(channel, severity) 들을 삭제
```yaml
    labels:
      channel: default
      severity: critical
      product: zcp-public
      priority: P4
```
